### PR TITLE
Fix #155: Replace O(n) visit ID collision loop with atomic counter

### LINKED ISSUE #155: [Bug] v5.4 performance regression: information_schema queries and unbounded collision loop cause 503 errors
**Source**: [wp.org support thread](https://wordpress.org/support/topic/l-broken-elements-on-dashboard-on-last-version-5-4/#post-18845772)

---

## Validation Result: Confirmed Bug

**Verdict**: VALID_BUG | **Confidence**: HIGH | **Severity**: Critical

### Summary

The v5.4 visit_id generation mechanism queries `information_schema.TABLES` on every pageview and includes an unbounded collision-detection loop, causing database saturation under moderate-to-high traffic.

### Root Cause

**Fault Location**: `src/Tracker/Session.php:101-122`, `src/Tracker/Processor.php:532-553`, `src/Tracker/Tracker.php:102-124`
**Mechanism**: `AUTO_INCREMENT` lookup via `information_schema.TABLES` (slow metadata query) + unbounded `do...while` loop for collision detection generates O(n) DB queries per request.

**Causal Chain**:
- Visitor pageview → `Tracker::slimtrack()` (priority 5, blocks rendering)
  → `Session::ensureVisitId()` → queries `information_schema.TABLES` (metadata lock)
    → checks for ID collision → loops incrementing + querying until free ID found
      → under concurrent traffic: many requests loop simultaneously → DB connection exhaustion → 503

**5 Whys**:
1. 503 errors → DB connection pool exhausted
2. Pool exhausted → each request holds connection during sequential queries
3. Sequential queries → visit_id collision loop fires multiple queries per request
4. Loop fires often → `AUTO_INCREMENT` returns stale values under concurrent inserts (ROOT CAUSE)

### Reproduction Steps

**Preconditions**: WP Slimstat 5.4+, server-side tracking (default), 10k+ rows in `slim_stats`

1. Activate WP Slimstat with default settings
2. Generate 20+ concurrent pageviews (load test or real traffic)
3. Observe degraded response times and eventual 503 errors
4. Confirm via `SHOW PROCESSLIST`: multiple `information_schema` and `slim_stats` queries queued

**Expected**: Tracking doesn't impact page load
**Actual**: 3-5+ DB queries per pageview minimum; unbounded loop under collisions

### Code References

| File | Lines | Description |
|------|-------|-------------|
| `src/Tracker/Session.php` | 101-122 | `information_schema` query + unbounded collision loop |
| `src/Tracker/Processor.php` | 532-553 | Identical pattern in consent upgrade path |
| `src/Tracker/Tracker.php` | 102-124 | Identical pattern in legacy tracker |
| `src/Tracker/Ajax.php` | 208-254 | `FOR UPDATE` transaction locking |
| `wp-slimstat.php` | 227 | Synchronous tracking at `wp` priority 5 |

### Security Note

If implementing a fix based on this analysis:
- Verify the fix doesn't introduce new vulnerabilities
- Run security linting (SAST) on changed code
- Check for OWASP Top 10 in any new code paths

---

*Validated via `qa-issue-validate` skill ([jaan.to](https://jaan.to) plugin)*

### PR DESCRIPTION
**Pull request by ParhamTehrani**
Performance fix for visit ID generation that caused 503 errors under high traffic.
Close #155 
Before: Query to information_schema.TABLES + unbounded do...while loop
After: Atomic increment via LAST_INSERT_ID() - always exactly 2 queries

- Add VisitIdGenerator class with thread-safe atomic counter
- Update Tracker.php, Session.php, Processor.php to use new generator
- Add counter initialization on plugin activation/upgrade

### Describe your changes
...

### Submission Review Guidelines:

- I have performed a self-review of my code
- If it is a core feature, I have added thorough tests.
- Will this be part of a product update? If yes, please write one phrase about this update.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/).
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.
- My code follows the style guidelines of this project
- I have updated the change-log in `CHANGELOG.md`.

### Type of change

-   [ ] Fix - Fixes an existing bug
-   [ ] Add - Adds functionality
-   [ ] Update - Update existing functionality
-   [ ] Dev - Development related task
-   [ ] Tweak - A minor adjustment to the codebase
-   [ ] Performance - Address performance issues
-   [ ] Enhancement - Improvement to existing functionality

## Summary by CodeRabbit

* **Refactor**
  * Replaced the previous database-driven visit ID allocation with an atomic, single-step generator to improve performance and eliminate collision checks.
* **Bug Fixes**
  * Added a one-time counter initialization during environment setup to ensure reliable visit ID sequencing and reduce initialization races.

### CODE REVIEW

File: src/Tracker/VisitIdGenerator.php [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+            "UPDATE {$wpdb->options} SET option_value = LAST_INSERT_ID(option_value + 1) WHERE option_name = %s",
+            self::OPTION_NAME
+        ));
+
+        if ($result === false) {
+            return self::fallbackGenerateVisitId();
+        }
+
+        // Get the value that was set by LAST_INSERT_ID()
+        $visit_id = $wpdb->get_var("SELECT LAST_INSERT_ID()");
```
Comment (parhumm) [inline src/Tracker/VisitIdGenerator.php]: `LAST_INSERT_ID()` is connection-scoped, so this two-step sequence is only safe if both statements hit the same underlying MySQL handle. Slimstat already supports swapping the wpdb implementation via `slimstat_custom_wpdb`, and HyperDB/LudicrousDB-style routers commonly send writes and reads to different connections. In that setup the `UPDATE` can hit the writer while `SELECT LAST_INSERT_ID()` runs on a reader and returns `0` or an unrelated insert id, which would assign the wrong `visit_id`. This needs to be collapsed into a single statement/connection-safe primitive or guarded so split-db installs do not silently generate bad IDs.

File: src/Tracker/VisitIdGenerator.php [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+        self::ensureCounterExists();
+
+        // Atomic increment using LAST_INSERT_ID()
+        // This sets LAST_INSERT_ID to the new value and returns it atomically
+        $result = $wpdb->query($wpdb->prepare(
+            "UPDATE {$wpdb->options} SET option_value = LAST_INSERT_ID(option_value + 1) WHERE option_name = %s",
+            self::OPTION_NAME
+        ));
+
+        if ($result === false) {
```
Comment (parhumm) [inline src/Tracker/VisitIdGenerator.php]: `$wpdb->query()` returns `0` when the `UPDATE` matches no rows, not just `false` on SQL errors. If the counter option is missing here because `add_option()` failed, the row was deleted concurrently, or a stale cache/db split left `ensureCounterExists()` out of sync, this branch still falls through to `SELECT LAST_INSERT_ID()`. MySQL then reuses the connection's previous insert id instead of taking the fallback path, so we can assign a stale/wrong `visit_id`. Treat anything other than exactly one affected row as failure before reading `LAST_INSERT_ID()`.

**Comment by parhumm** [comment]
## Human QA Checklist

### Fresh Install
- [ ] Activate plugin on a clean WordPress site
- [ ] Verify `slimstat_visit_id_counter` option is created in `wp_options`
- [ ] Visit the frontend — confirm a pageview is recorded with a valid `visit_id`
- [ ] Visit again in the same session — confirm `visit_id` stays the same (session continuity)
- [ ] Open a second browser/incognito — confirm a **different** `visit_id` is assigned

### Upgrade Path
- [ ] Install the **previous** version (5.4.x), generate some traffic (5+ pageviews)
- [ ] Note the current max `visit_id` in `wp_slim_stats`
- [ ] Upgrade to this PR branch
- [ ] Verify `slimstat_visit_id_counter` is initialized to >= the old max `visit_id`
- [ ] New visits get IDs **higher** than the old max (no ID reuse or gaps backward)

### Concurrent Traffic (Core Test)
- [ ] Use a load testing tool (e.g. `ab -n 100 -c 10`) or open 10+ tabs simultaneously
- [ ] All requests complete without 503 errors
- [ ] Every recorded row has a **unique** `visit_id` (no duplicates):
  ```sql
  SELECT visit_id, COUNT(*) c FROM wp_slim_stats GROUP BY visit_id HAVING c > 1;
  ```
- [ ] Counter in `wp_options` incremented correctly (value = max visit_id in table)

### Fallback Behavior
- [ ] Temporarily rename the `slimstat_visit_id_counter` option row in DB
- [ ] Visit the site — `ensureCounterExists()` should re-create it automatically
- [ ] Pageview is still tracked with a valid `visit_id`

### Session Continuity
- [ ] Start a visit, navigate 3-4 pages — all pageviews share the same `visit_id`
- [ ] Wait for session timeout (default 30 min or lower it for testing)
- [ ] Visit again — a **new** `visit_id` is assigned

### Admin & Reporting
- [ ] Reports page loads correctly, showing visits with proper visit IDs
- [ ] "Visits" vs "Pageviews" counts are consistent with expected behavior
- [ ] No PHP warnings/errors in `debug.log` related to visit ID generation

### Database
- [ ] Verify no queries to `information_schema.TABLES` in the tracking path (enable query logging or use Query Monitor)
- [ ] Confirm only 2 queries per visit ID generation: `UPDATE ... LAST_INSERT_ID()` + `SELECT LAST_INSERT_ID()`

**Review by parhumm — APPROVED** [review]
Re-reviewed after commit a16bd1ba. No additional blocking findings in the current diff from static review. Remaining gap is manual runtime/load verification against a WordPress install.
